package com.baste;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import com.baste.enums.Personaje;

/**
 * Created by Fran on 21/07/2014.
 */
public class UtilesSonidos {
    private static List<Sonido> sonidos = new ArrayList<Sonido>();

    public static List<Sonido> getListaTodos() {
        return sonidos;
    }

    public static void sonidos() {
        if (sonidos.isEmpty()) {
            sonidos.add(new Sonido("45 años con hipo", R.raw.anos_con_hipo, Personaje.KENT));
            sonidos.add(new Sonido("64 lonchas de queso americano", R.raw.lonchas, Personaje.HOMER));
            sonidos.add(new Sonido("A fregar!", R.raw.a_fregar, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=j4vAlh47Rps"));
            sonidos.add(new Sonido("A mi me llaman Ottooo y haré el papel de Pablooo", R.raw.otto, Personaje.OTROS).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/otto.3gp"));
            sonidos.add(new Sonido("A que te mato!", R.raw.aquetemato, Personaje.HOMER));
            sonidos.add(new Sonido("A que te tiro, te tiro, te tiro", R.raw.aqttiro, Personaje.WIGGUM).setVideoUrl("http://www.youtube.com/watch?v=j-ILsXmqSxg"));
            sonidos.add(new Sonido("A ti no te puedo mentir Marge...", R.raw.mentirmargue, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Actor sec. Bob", R.raw.bob, Personaje.OTROS).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/Actor%20sec.%20Bob.3gp"));
            sonidos.add(new Sonido("Adiós al Badulake", R.raw.adiosbadulake, Personaje.CANCIONES, Personaje.APU).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/badulake.3gp"));
            sonidos.add(new Sonido("Al estilo Max Power", R.raw.estilomaxpower, Personaje.HOMER, Personaje.BART).setVideoUrl("http://www.youtube.com/watch?v=nOg1-7up2-w"));
            sonidos.add(new Sonido("Alarma todo va como Dios manda", R.raw.alarmatodobien, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=pJaWqxAxy7c"));
            sonidos.add(new Sonido("Algunos de vosotros sabe volver a casa?", R.raw.volver_a_casa, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=Y3SLbBb2Iv8"));
            sonidos.add(new Sonido("Amanece, atardece...", R.raw.amanece_atardece, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=wvN2vzfCYac"));
            sonidos.add(new Sonido("Amen hermano!", R.raw.amen_hermano, Personaje.HOMER, Personaje.BART).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/amen_hermano.3gp"));
            sonidos.add(new Sonido("Apu tras trabajar 96 horas seguidas", R.raw.apu_96h, Personaje.APU));
            sonidos.add(new Sonido("Aquí está Johnny", R.raw.aquiesta, Personaje.HOMER));
            sonidos.add(new Sonido("Astu pata pota ita hija", R.raw.astu, Personaje.HOMER, Personaje.MARGE).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/Astu%20pata%20pota%20ita%20hija.3gp"));
            sonidos.add(new Sonido("Ayatolá", R.raw.ayatola, Personaje.HOMER));
            sonidos.add(new Sonido("Barney", R.raw.barney, Personaje.BARNEY));
            sonidos.add(new Sonido("Bauuuuula bauuuuula", R.raw.baula, Personaje.BART, Personaje.LISA).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/baula.3gp"));
            sonidos.add(new Sonido("Burns imitando a Elvis", R.raw.elvis, Personaje.BURNS).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/elvis.3gp"));
            sonidos.add(new Sonido("Buuuuarns", R.raw.buuuuarns, Personaje.BURNS, Personaje.SMITHER));
            sonidos.add(new Sonido("Cama arriba, cama abajo", R.raw.cama, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=34mNkx6KeB8"));
            sonidos.add(new Sonido("Cambio de voz de Homer", R.raw.cambiodevoz, Personaje.HOMER, Personaje.ABUELO).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/cambiodevoz.3gp"));
            sonidos.add(new Sonido("Campamento Krusty", R.raw.campamento_krusty, Personaje.CANCIONES).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/campamento.3gp"));
            sonidos.add(new Sonido("Cara de red", R.raw.caradered, Personaje.HOMER, Personaje.LENNY));
            sonidos.add(new Sonido("Carta", R.raw.carta, Personaje.HOMER));
            sonidos.add(new Sonido("Catapum pum", R.raw.catapum, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Cañonero", R.raw.canonero, Personaje.CANCIONES));
            sonidos.add(new Sonido("Cerveceame", R.raw.cerveceame, Personaje.HOMER, Personaje.CANCIONES));
            sonidos.add(new Sonido("Chiflasi el payaso", R.raw.chiflasi, Personaje.HOMER));
            sonidos.add(new Sonido("Chu chu chu", R.raw.chu, Personaje.RALPH));
            sonidos.add(new Sonido("Cojo otro muelle", R.raw.cojootromuelle, Personaje.HOMER, Personaje.MARGE, Personaje.CANCIONES).setVideoUrl("http://www.youtube.com/watch?v=BHdkKgf1JDE"));
            sonidos.add(new Sonido("Como mola dormir", R.raw.como_mola_dormir, Personaje.RALPH));
            sonidos.add(new Sonido("Con la de hierro que tiene", R.raw.con_la_de_hierro_que_tiene, Personaje.BART, Personaje.MARGE).setVideoUrl("http://www.youtube.com/watch?v=y3i10UQLLP8"));
            sonidos.add(new Sonido("Concurso de eructos", R.raw.eructo, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=W9g_dbcjQWg"));
            sonidos.add(new Sonido("Confesiones en el Taxi", R.raw.taxi, Personaje.HOMER).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/taxi.3gp"));
            sonidos.add(new Sonido("Consejo 1º día de colegio", R.raw.consejo_1_dia_de_colegio, Personaje.HOMER, Personaje.ABUELO));
            sonidos.add(new Sonido("Corre huevo", R.raw.correhuevo, Personaje.HOMER, Personaje.LENNY));
            sonidos.add(new Sonido("Corre plátano!", R.raw.corre_platano, Personaje.RALPH));
            sonidos.add(new Sonido("Cosquillas asesinas", R.raw.cosquillas_asesinas, Personaje.RALPH));
            sonidos.add(new Sonido("Cua cua cua", R.raw.cua, Personaje.HOMER));
            sonidos.add(new Sonido("Cual es tu país menos favorito?", R.raw.paisfavorito, Personaje.OTROS));
            sonidos.add(new Sonido("Cuchara", R.raw.cuchara, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Cállese Jueza!!", R.raw.callese_jueza, Personaje.HOMER));
            sonidos.add(new Sonido("Código Azul", R.raw.codigo_azul, Personaje.HOMER, Personaje.DOCTOR, Personaje.LISA));
            sonidos.add(new Sonido("D'oh", R.raw.doh, Personaje.HOMER));
            sonidos.add(new Sonido("D'oh (x30)", R.raw.doh30, Personaje.HOMER));
            sonidos.add(new Sonido("Dame ese bate", R.raw.dameesebate, Personaje.HOMER));
            sonidos.add(new Sonido("Debería ser una central nuclear", R.raw.deberia_ser_una_central, Personaje.RALPH));
            sonidos.add(new Sonido("Decano eres un membrillo!", R.raw.membrillo, Personaje.HOMER));
            sonidos.add(new Sonido("Deja a Maggie, ha muerto", R.raw.volverapormaggie, Personaje.HOMER, Personaje.MARGE, Personaje.LISA).setVideoUrl("http://www.youtube.com/watch?v=fZBgPjGZwi8"));
            sonidos.add(new Sonido("Dejar de hacer estupideces", R.raw.estupidez, Personaje.HOMER));
            sonidos.add(new Sonido("Dentro del pecho ay algo que hace Bom Bom", R.raw.dentro_del_pecho, Personaje.HOMER));
            sonidos.add(new Sonido("Desearía estar muerto", R.raw.desearia_estar_muerto, Personaje.HOMER));
            sonidos.add(new Sonido("Dinosaurio", R.raw.dinosaurio, Personaje.HOMER, Personaje.MARGE).setVideoUrl("http://www.youtube.com/watch?v=hsXvl-yVAlQ"));
            sonidos.add(new Sonido("Dinosaurio inamovible", R.raw.dino, Personaje.HOMER, Personaje.KENT));
            sonidos.add(new Sonido("Don Culo Gordo", R.raw.don_culo_gordo, Personaje.BART, Personaje.MOE));
            sonidos.add(new Sonido("Don Mis Partes", R.raw.mispartes, Personaje.BART, Personaje.MOE));
            sonidos.add(new Sonido("Don Pi Topocho", R.raw.don_pi_topocho, Personaje.BART, Personaje.MOE));
            sonidos.add(new Sonido("Dos filetones con salsa especial", R.raw.dosfiletones, Personaje.HOMER));
            sonidos.add(new Sonido("Dr. Zaius", R.raw.zaius, Personaje.CANCIONES).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/Dr.%20Zaius.3gp"));
            sonidos.add(new Sonido("Droga", R.raw.droga, Personaje.SMITHER));
            sonidos.add(new Sonido("Dudidudidu tu padre! Renacuajo!", R.raw.dudidudidu_tu_padre_renacuajo, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=7CIGOc2glqs"));
            sonidos.add(new Sonido("Duff para mi, Duff para ti", R.raw.duff, Personaje.CANCIONES).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/Duff%20para%20ti%2C%20Duff%20para%20mi.3gp"));
            sonidos.add(new Sonido("Dulce cu", R.raw.dulce_cu, Personaje.HOMER).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/dulce%20cu.3gp"));
            sonidos.add(new Sonido("Día especial? Feliz día de San Valentín?!", R.raw.diaespecial, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Dónde está mi bebe?", R.raw.bebe, Personaje.RALPH).setVideoUrl("http://www.youtube.com/watch?v=tMEZql3AZw4"));
            sonidos.add(new Sonido("Ebrios patanes del jurado", R.raw.ebrios_patanes, Personaje.HOMER));
            sonidos.add(new Sonido("Ehh Homer", R.raw.ehhomer, Personaje.FLANDERS).setVideoUrl("http://www.youtube.com/watch?v=GZDhky2ifgg"));
            sonidos.add(new Sonido("El alcohol", R.raw.alcohol, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=cFGRdsFyroE"));
            sonidos.add(new Sonido("El aliento de mi gato huele a comida de gato", R.raw.aliento_gato, Personaje.RALPH).setVideoUrl("http://www.youtube.com/watch?v=i0vI41sQGeA"));
            sonidos.add(new Sonido("El fantástico Ralph", R.raw.fantastico_ralph, Personaje.RALPH));
            sonidos.add(new Sonido("El hombre del saco", R.raw.hombre_saco, Personaje.HOMER, Personaje.BART, Personaje.LISA).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/El-hombre-del-saco.3gp"));
            sonidos.add(new Sonido("El mayor suspenso de tu vida", R.raw.mayor_suspenso, Personaje.RALPH));
            sonidos.add(new Sonido("El número del 091", R.raw.homer_091, Personaje.HOMER));
            sonidos.add(new Sonido("El peso atómico del salchichonio", R.raw.tablas_periodicas, Personaje.OTROS));
            sonidos.add(new Sonido("El rey de la UVI", R.raw.reyuvi, Personaje.BART).setVideoUrl("http://www.youtube.com/watch?v=8MbA4Jli2vA"));
            sonidos.add(new Sonido("El sol me acaricia con sus rayos", R.raw.sol_acaricia, Personaje.OTROS));
            sonidos.add(new Sonido("Empecemos por lo básico", R.raw.basico, Personaje.OTROS).setVideoUrl("http://www.youtube.com/watch?v=JLOQ-GsW9KY"));
            sonidos.add(new Sonido("En esta casa obedecemos las leyes de la termodinámica!", R.raw.termodinamica, Personaje.HOMER));
            sonidos.add(new Sonido("Entendido! Gato en la Caldera!", R.raw.gatocaldera, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Era mi primerito día", R.raw.primerito, Personaje.HOMER));
            sonidos.add(new Sonido("Es Chinatown", R.raw.chinatown, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Es como si no llevara nada", R.raw.es_como_si_no_llevaras_nada, Personaje.HOMER, Personaje.FLANDERS).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/es%20como%20si%20no%20llevaras%20nada.3gp"));
            sonidos.add(new Sonido("Es el filete más grande que tienen? Sólo de 2 kilos?", R.raw.solomillon, Personaje.HOMER).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/solomillon.3gp"));
            sonidos.add(new Sonido("Es la chapuza total", R.raw.chapuzatotal, Personaje.CANCIONES).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/chapuzatotal.3gp"));
            sonidos.add(new Sonido("Es un ladrón", R.raw.esunladron, Personaje.HOMER, Personaje.SKINNER));
            sonidos.add(new Sonido("Ese es mi Tomasito!", R.raw.tomasito, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=SSNqsPG24WE"));
            sonidos.add(new Sonido("Eso es mentira, so marrana!", R.raw.mentira, Personaje.HOMER));
            sonidos.add(new Sonido("Esquirla", R.raw.esquirla, Personaje.OTROS));
            sonidos.add(new Sonido("Esta yegua no es mi vieja yegua gris", R.raw.yegua, Personaje.OTROS).setVideoUrl("http://www.youtube.com/watch?v=IccG3MKlN_E"));
            sonidos.add(new Sonido("Estela! Estela!", R.raw.estela, Personaje.FLANDERS).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/estela.3gp"));
            sonidos.add(new Sonido("Estornudo Ogdenville", R.raw.ogdenville, Personaje.OTROS));
            sonidos.add(new Sonido("Estoy buscando al señor soborno", R.raw.estoybus, Personaje.HOMER, Personaje.WIGGUM));
            sonidos.add(new Sonido("Estoy haciendo feliz a la gente", R.raw.estoyhaci, Personaje.HOMER));
            sonidos.add(new Sonido("Está ladrando el perro", R.raw.esta_ladrando_el_perro, Personaje.HOMER));
            sonidos.add(new Sonido("Estás mirando señoras desnudas?", R.raw.estamise, Personaje.SKINNER));
            sonidos.add(new Sonido("Excelente", R.raw.srburns, Personaje.BURNS));
            sonidos.add(new Sonido("Exclusiones", R.raw.exclusiones, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=L7Q9-2CuXfI"));
            sonidos.add(new Sonido("Farfala vendetta", R.raw.farfala_vendetta, Personaje.OTROS));
            sonidos.add(new Sonido("Flaaanders", R.raw.flaaanders, Personaje.HOMER, Personaje.FLANDERS));
            sonidos.add(new Sonido("Gafas nuevas?", R.raw.gafas_nuevas, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Ganas de matar aumentando", R.raw.ganas, Personaje.HOMER));
            sonidos.add(new Sonido("Garantía adicional? No tengo nada que perder...", R.raw.garantia, Personaje.HOMER, Personaje.MOE).setVideoUrl("http://www.youtube.com/watch?v=LY5Fuk-Nwwg"));
            sonidos.add(new Sonido("Giliiii", R.raw.giliiii, Personaje.HOMER));
            sonidos.add(new Sonido("Golpe de remo", R.raw.golpederemo, Personaje.OTROS));
            sonidos.add(new Sonido("Guapito, más patatitas?", R.raw.patatitas, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Hable mas alto, llevo una toalla", R.raw.toalla, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=amFr5IMuXHs"));
            sonidos.add(new Sonido("Haciendo bebes", R.raw.haciendo_bebes, Personaje.RALPH, Personaje.WIGGUM).setVideoUrl("http://www.youtube.com/watch?v=KrSMKlDvxCU"));
            sonidos.add(new Sonido("Has devuelto todas las armas?", R.raw.sinarmas, Personaje.HOMER, Personaje.BART).setVideoUrl("http://www.youtube.com/watch?v=4PIHB6zowIQ"));
            sonidos.add(new Sonido("He encontrado una cosa!", R.raw.he_encontrado, Personaje.RALPH));
            sonidos.add(new Sonido("Hermano Hans Topo", R.raw.hermano_hans_topo, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=3lwmkci2ajk"));
            sonidos.add(new Sonido("Hijo de perrilla", R.raw.hijodeperrilla, Personaje.FLANDERS).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/Hijo%20de%20Perrilla.3gp"));
            sonidos.add(new Sonido("Hipopótamo", R.raw.hipopotamo, Personaje.HOMER).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/hipopotamo.3gp"));
            sonidos.add(new Sonido("Hola, holita", R.raw.flanders, Personaje.FLANDERS));
            sonidos.add(new Sonido("Hola, soy el Sr. Burns", R.raw.holaaa, Personaje.HOMER));
            sonidos.add(new Sonido("Hombre arrepentido", R.raw.hombrearrepentido, Personaje.HOMER));
            sonidos.add(new Sonido("Hombre feliz", R.raw.hombrefeliz, Personaje.HOMER).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/hombrefeliz.3gp"));
            sonidos.add(new Sonido("Homer Junior", R.raw.homer_junior, Personaje.HOMER, Personaje.BART));
            sonidos.add(new Sonido("Homer Simpson caza empollones", R.raw.cazaempollones, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=oCCOH0Hzzlc"));
            sonidos.add(new Sonido("Homer bailando la raspa", R.raw.laraspa, Personaje.HOMER));
            sonidos.add(new Sonido("Homer comunista", R.raw.homer_comunista, Personaje.ABUELO));
            sonidos.add(new Sonido("Homer con gafas", R.raw.homergafas, Personaje.HOMER));
            sonidos.add(new Sonido("Homer contra la gallina", R.raw.gallina, Personaje.HOMER));
            sonidos.add(new Sonido("Homer en la universidad", R.raw.homer_uni, Personaje.HOMER));
            sonidos.add(new Sonido("Homer me parece que no has pensado lo que acabas de decir", R.raw.hedichoyuguu, Personaje.HOMER, Personaje.MARGE).setVideoUrl("http://www.youtube.com/watch?v=Z0FZmOgRdxs"));
            sonidos.add(new Sonido("Homer que lento eres", R.raw.lento, Personaje.HOMER, Personaje.LENNY));
            sonidos.add(new Sonido("Homer, me prestas tus calzoncillos?", R.raw.examen_medico, Personaje.HOMER, Personaje.LENNY));
            sonidos.add(new Sonido("Horóscopo Homer", R.raw.horoscopo_homer, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=54PR__BlYqs"));
            sonidos.add(new Sonido("Implícito Lisa o ilícito?", R.raw.implicito, Personaje.HOMER, Personaje.LISA));
            sonidos.add(new Sonido("Intruso", R.raw.intruso, Personaje.HOMER, Personaje.WIGGUM, Personaje.FLANDERS));
            sonidos.add(new Sonido("Jaque mate", R.raw.jaque_mate, Personaje.BART));
            sonidos.add(new Sonido("Jardín del Edén", R.raw.jardindeleden, Personaje.CANCIONES).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/eden.3gp"));
            sonidos.add(new Sonido("Juego con mi melocotonero", R.raw.juego_con_mi_melocotonero, Personaje.LISA).setVideoUrl("http://www.youtube.com/watch?v=oet-EpQ5MEY"));
            sonidos.add(new Sonido("Khlav kalash", R.raw.khlav_kalash, Personaje.OTROS));
            sonidos.add(new Sonido("La caja", R.raw.la_caja, Personaje.BURNS));
            sonidos.add(new Sonido("La cocaína Lisa", R.raw.cocaina, Personaje.HOMER, Personaje.LISA).setVideoUrl("http://www.youtube.com/watch?v=z8Hvqzh5avU"));
            sonidos.add(new Sonido("La ligas", R.raw.la_ligas, Personaje.RALPH, Personaje.BURNS).setVideoUrl("http://www.youtube.com/watch?v=EwegQonIhjU"));
            sonidos.add(new Sonido("La madre que me... mi coche", R.raw.micoche, Personaje.HOMER));
            sonidos.add(new Sonido("La muerteeee", R.raw.lamuerte, Personaje.ABUELO, Personaje.LISA));
            sonidos.add(new Sonido("La niña sabe demasiado", R.raw.sabe_demasiado, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=mPsp1xwtuqA"));
            sonidos.add(new Sonido("La patata no se puede poseer", R.raw.lapatata, Personaje.HOMER));
            sonidos.add(new Sonido("La que teníamos antes también me gritaba", R.raw.tmb_megritaba, Personaje.RALPH));
            sonidos.add(new Sonido("La súper compra de Homer", R.raw.compra, Personaje.HOMER));
            sonidos.add(new Sonido("La última vez que lo vi estaba dentro de una bolsa de plástico", R.raw.red, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=blfyvYg_KqY"));
            sonidos.add(new Sonido("Las 3 frases cortas", R.raw.las3frases, Personaje.HOMER));
            sonidos.add(new Sonido("Las 5 fases de la muerte", R.raw.fases, Personaje.HOMER, Personaje.DOCTOR).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/5fases.3gp"));
            sonidos.add(new Sonido("Le daré un simple toquecito", R.raw.le_dare_un_simple_toquecito, Personaje.HOMER, Personaje.DOCTOR).setVideoUrl("http://www.youtube.com/watch?v=duu-hPPbmFA"));
            sonidos.add(new Sonido("Limpio mi escopeta sin el seguro, sin el seguro, sin el seguro", R.raw.sinelseguro, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=2YbmzLtM9Vc"));
            sonidos.add(new Sonido("Lisa es una niña de mi cole", R.raw.lisa_nina_mi_cole, Personaje.RALPH));
            sonidos.add(new Sonido("Llevo 25 años esperando este momento", R.raw.anosperando, Personaje.BURNS, Personaje.SMITHER));
            sonidos.add(new Sonido("Lleváoslo muchachos", R.raw.llevaoslo_muchachos, Personaje.WIGGUM, Personaje.BART).setVideoUrl("http://www.youtube.com/watch?v=AkSsQ6V2E4U"));
            sonidos.add(new Sonido("Lo mio pa mi", R.raw.lomiopami, Personaje.CANCIONES));
            sonidos.add(new Sonido("Loco cósmico", R.raw.lococosmico, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=cqm3SXLvg7o"));
            sonidos.add(new Sonido("Los Canteros", R.raw.canteros, Personaje.CANCIONES).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/canteros.3gp"));
            sonidos.add(new Sonido("Los altos precios del Badulaque", R.raw.apu_ladron, Personaje.APU));
            sonidos.add(new Sonido("Luchar luchar luchar!!!", R.raw.luchar, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Lápices a la plancha", R.raw.lapices_pancha, Personaje.RALPH, Personaje.WIGGUM));
            sonidos.add(new Sonido("Mal en lengua", R.raw.malenlengua, Personaje.RALPH, Personaje.SKINNER).setVideoUrl("http://www.youtube.com/watch?v=17htVQdt8NQ"));
            sonidos.add(new Sonido("Mamá se llevó esas pilas", R.raw.mamasellevoesaspilas, Personaje.HOMER, Personaje.CANCIONES));
            sonidos.add(new Sonido("Marchando 700 Krusty hamburguesas", R.raw.setecientas, Personaje.HOMER, Personaje.BART).setVideoUrl("http://www.youtube.com/watch?v=tix9FWLg1q8"));
            sonidos.add(new Sonido("Marge", R.raw.marge, Personaje.MARGE));
            sonidos.add(new Sonido("Mateo 21:17", R.raw.mateo2117, Personaje.HOMER));
            sonidos.add(new Sonido("Max Power", R.raw.max_power, Personaje.HOMER, Personaje.CANCIONES));
            sonidos.add(new Sonido("Me aburro", R.raw.meaburro, Personaje.HOMER));
            sonidos.add(new Sonido("Me cago en", R.raw.mecagoen, Personaje.HOMER));
            sonidos.add(new Sonido("Me dijo que quemara cosas", R.raw.vi_un_gnomo, Personaje.RALPH, Personaje.BART).setVideoUrl("http://www.youtube.com/watch?v=V0gn5P1Oulg"));
            sonidos.add(new Sonido("Me duele el bolsillo", R.raw.me_duele_el_bolsillo, Personaje.HOMER));
            sonidos.add(new Sonido("Me lavo con una esponja atada a un palo", R.raw.me_lavo_con_una_esponja_atada_a_un_palo, Personaje.BART));
            sonidos.add(new Sonido("Me quieres comer con los ojos eh lobito", R.raw.comer_ojos, Personaje.HOMER).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/Me%20Quieres%20Comer%20Con%20Los%20Ojos%20Eh%20Lobito.3gp"));
            sonidos.add(new Sonido("Meto cuchillo saco tripas", R.raw.metocuchillo, Personaje.BART).setVideoUrl("http://www.youtube.com/watch?v=AOKQ-vDONmA"));
            sonidos.add(new Sonido("Mi capacidad de atención es reducida", R.raw.mi_capacidad_de_atencion_es_reducida, Personaje.HOMER));
            sonidos.add(new Sonido("Mi familia me pide vino", R.raw.mi_familia_me_pide_vino, Personaje.OTROS).setVideoUrl("http://www.youtube.com/watch?v=X-fXQ2u9HKg"));
            sonidos.add(new Sonido("Mi gato se llama guantes", R.raw.gato_guantes, Personaje.RALPH));
            sonidos.add(new Sonido("Milhouse dile a Bart que venga", R.raw.milhouse_dile_a_bart_que_venga, Personaje.HOMER, Personaje.MILHOUSE).setVideoUrl("http://www.youtube.com/watch?v=yaXUaQ34IVk"));
            sonidos.add(new Sonido("Milhouse y los aspersores", R.raw.aspersores, Personaje.MILHOUSE).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/aspersores.3gp"));
            sonidos.add(new Sonido("Mira que risa me da", R.raw.mira_que_risa_me_da, Personaje.CANCIONES));
            sonidos.add(new Sonido("Mirad, un niño con tetas", R.raw.mirad_un_nino_con_tetas, Personaje.HOMER));
            sonidos.add(new Sonido("Mire al frente señor", R.raw.mirealfrente, Personaje.SKINNER).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/mirealfrente.3gp"));
            sonidos.add(new Sonido("Mmmm que bien leer", R.raw.leer, Personaje.HOMER, Personaje.BART).setVideoUrl("http://www.youtube.com/watch?v=0aSYdC0VUQY"));
            sonidos.add(new Sonido("Monorraíl", R.raw.monorail, Personaje.CANCIONES).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/monorail.3gp"));
            sonidos.add(new Sonido("Moraleja", R.raw.moraleja, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=TytesLwsL8o"));
            sonidos.add(new Sonido("Mosquis", R.raw.mosquis, Personaje.HOMER));
            sonidos.add(new Sonido("Mosquis! Un sexteto cervecil!", R.raw.mosquisun, Personaje.HOMER));
            sonidos.add(new Sonido("Multiplícate por cero", R.raw.x0, Personaje.BART));
            sonidos.add(new Sonido("Na na na líder", R.raw.lider, Personaje.CANCIONES).setVideoUrl("http://www.youtube.com/watch?v=DmXRcPvsTD0"));
            sonidos.add(new Sonido("Necesitamos panchitos", R.raw.necepanchi, Personaje.WIGGUM));
            sonidos.add(new Sonido("Nelson", R.raw.nelson, Personaje.NELSON));
            sonidos.add(new Sonido("Nelson colleja", R.raw.nelsoncolleja, Personaje.NELSON));
            sonidos.add(new Sonido("Ningún problema de corazón?", R.raw.corazon, Personaje.HOMER, Personaje.BURNS, Personaje.ABUELO).setVideoUrl("http://www.youtube.com/watch?v=aTN05PkuMN4"));
            sonidos.add(new Sonido("Niño Jesús salvame", R.raw.ninojesus, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=3LJCt0WCMB8"));
            sonidos.add(new Sonido("Niño tiburón", R.raw.ninotiburon, Personaje.HOMER, Personaje.BART));
            sonidos.add(new Sonido("Niños niños futuro futuro", R.raw.ninosfuturo, Personaje.CANCIONES).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/ninos.3gp"));
            sonidos.add(new Sonido("No conquistas nada con una ensalada", R.raw.no_conquistas_nada_con_una_ensalada, Personaje.CANCIONES));
            sonidos.add(new Sonido("No digas venganza", R.raw.venganza, Personaje.HOMER));
            sonidos.add(new Sonido("No es hora de llorar", R.raw.noeshoradellorar, Personaje.HOMER));
            sonidos.add(new Sonido("No me comáis", R.raw.nomecomais, Personaje.BART, Personaje.MARGE, Personaje.LISA).setVideoUrl("http://www.youtube.com/watch?v=yZbMnnQM5QY"));
            sonidos.add(new Sonido("No paso nada", R.raw.nopasonada, Personaje.RALPH));
            sonidos.add(new Sonido("No puedo dormir me come el payaso", R.raw.no_puedo_dormir, Personaje.BART).setVideoUrl("http://www.youtube.com/watch?v=LunbsJ1WKFw"));
            sonidos.add(new Sonido("No se oye", R.raw.noseoye, Personaje.ABUELO));
            sonidos.add(new Sonido("No se oye nada", R.raw.no_se_oye_nada, Personaje.ABUELO));
            sonidos.add(new Sonido("No soy una fruta", R.raw.no_soy_una_fruta, Personaje.RALPH, Personaje.LISA));
            sonidos.add(new Sonido("No tocar nada", R.raw.no_tocar_nada, Personaje.HOMER));
            sonidos.add(new Sonido("No volveré a probar la cerveza", R.raw.cervezademe10, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=0sWEpufMff8"));
            sonidos.add(new Sonido("No vuelvo a probar el chili", R.raw.chili, Personaje.HOMER));
            sonidos.add(new Sonido("Nos manifestaremos como hicimos ayer", R.raw.nos_manifestaremos, Personaje.CANCIONES, Personaje.LISA));
            sonidos.add(new Sonido("Núcelar", R.raw.nucelar, Personaje.HOMER));
            sonidos.add(new Sonido("Númelo 8", R.raw.numelo8, Personaje.BARNEY));
            sonidos.add(new Sonido("Oh Mindy", R.raw.mindy, Personaje.HOMER, Personaje.CANCIONES).setVideoUrl("http://www.youtube.com/watch?v=Fkp_o3CEvqs"));
            sonidos.add(new Sonido("Os prestaré toda mi atención", R.raw.osprest, Personaje.HOMER));
            sonidos.add(new Sonido("Pa loca tu", R.raw.palocatu, Personaje.HOMER));
            sonidos.add(new Sonido("Pago yo", R.raw.pagoyo, Personaje.HOMER).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/pagoyo.3gp"));
            sonidos.add(new Sonido("Papá hemos hecho una cosa muy mala", R.raw.papa_hemos_hecho_una_cosa_muy_mala, Personaje.HOMER, Personaje.LISA));
            sonidos.add(new Sonido("Pasooo", R.raw.pasooo, Personaje.OTROS));
            sonidos.add(new Sonido("Pato pato", R.raw.pato, Personaje.RALPH));
            sonidos.add(new Sonido("Pe pe pero el poncho", R.raw.poncho, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=SZ09SeTeo5Q"));
            sonidos.add(new Sonido("Peinado mariquita", R.raw.peinado_mariq, Personaje.HOMER, Personaje.BURNS, Personaje.LISA).setVideoUrl("http://www.youtube.com/watch?v=d1Y0VC9quiM"));
            sonidos.add(new Sonido("Pelos en la espalda", R.raw.pelos_espalda, Personaje.HOMER, Personaje.BART).setVideoUrl("http://www.youtube.com/watch?v=KGBPgsYLoGs"));
            sonidos.add(new Sonido("Pensamiento", R.raw.pensamiento, Personaje.HOMER));
            sonidos.add(new Sonido("Perdiditos", R.raw.perdiditos, Personaje.HOMER, Personaje.BART, Personaje.FLANDERS));
            sonidos.add(new Sonido("Pero que es un diorama?", R.raw.diorama, Personaje.RALPH));
            sonidos.add(new Sonido("Perro Ralph", R.raw.ralph_perro, Personaje.RALPH));
            sonidos.add(new Sonido("Picapiedra", R.raw.picapiedra, Personaje.HOMER, Personaje.CANCIONES));
            sonidos.add(new Sonido("Piña colonia", R.raw.pina_colonia, Personaje.HOMER, Personaje.CANCIONES));
            sonidos.add(new Sonido("Podrá detenernos, pero nunca vencerá a los cobras", R.raw.cobras, Personaje.HOMER).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/cobras.3gp"));
            sonidos.add(new Sonido("Polígrafo", R.raw.poligrafo, Personaje.HOMER));
            sonidos.add(new Sonido("Polígrafo Moe", R.raw.polimoe, Personaje.MOE));
            sonidos.add(new Sonido("Por el alcohol", R.raw.por_el_alcohol, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=gZrwjnLLxlM"));
            sonidos.add(new Sonido("Por qué todos huyen de mí?", R.raw.huyen, Personaje.RALPH));
            sonidos.add(new Sonido("Porque has aparcao al lao de mis viejos?", R.raw.porque_has_aparcao_al_lao_de_mis_viejos, Personaje.OTROS));
            sonidos.add(new Sonido("Pueblo de prostitutas", R.raw.prostitutas, Personaje.OTROS).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/prostitutas.3gp"));
            sonidos.add(new Sonido("Puñetazo en la nuca a Lenny", R.raw.punetazo_nuca, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=xJ6S-zlrZUc"));
            sonidos.add(new Sonido("Que le parta un rayo!", R.raw.qlepartaunrayo, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=sfrKK7kC8Ds"));
            sonidos.add(new Sonido("Que listo soy yo", R.raw.que_listo_soy_yo, Personaje.HOMER));
            sonidos.add(new Sonido("Que no es Batman!", R.raw.batman, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Que no tíos, que sin pelo no soy nada", R.raw.qnotios, Personaje.HOMER));
            sonidos.add(new Sonido("Que suerte", R.raw.que_suerte, Personaje.HOMER));
            sonidos.add(new Sonido("Queda detenido", R.raw.queda, Personaje.WIGGUM));
            sonidos.add(new Sonido("Quiero dejar esto bien claro", R.raw.quierodejar, Personaje.HOMER));
            sonidos.add(new Sonido("Quiero mi bocadillo", R.raw.qmboca, Personaje.HOMER));
            sonidos.add(new Sonido("Quisiera ser tan alto como la Luna", R.raw.quisiera, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Qué gran verdad ha dicho!", R.raw.granverdad, Personaje.HOMER));
            sonidos.add(new Sonido("Qué no, Lisa? Qué nooo?", R.raw.queno, Personaje.HOMER, Personaje.LISA));
            sonidos.add(new Sonido("Ralph en el baño", R.raw.ralph_bano, Personaje.RALPH, Personaje.SKINNER));
            sonidos.add(new Sonido("Ralph se encara con su dedo", R.raw.ralph_se_encara_con_su_dedo, Personaje.RALPH));
            sonidos.add(new Sonido("Rap yo no he sido", R.raw.rap, Personaje.BART, Personaje.CANCIONES).setVideoUrl("http://www.youtube.com/watch?v=tpG44oAb7g8"));
            sonidos.add(new Sonido("Rasca y Pica", R.raw.rascaypica, Personaje.CANCIONES));
            sonidos.add(new Sonido("Rasca y Pica (Fin)", R.raw.rascaypicafin, Personaje.CANCIONES));
            sonidos.add(new Sonido("Rasca, Pica y Poochie", R.raw.rascapicapoochie, Personaje.CANCIONES));
            sonidos.add(new Sonido("Scooby Doo puede hacer pupú, pero Jimmy Carter de risa se parter", R.raw.carter, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=FwcSeDeAmPc"));
            sonidos.add(new Sonido("Se os acusa de hacer que un policía haga ai ai", R.raw.ai_ai, Personaje.WIGGUM).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/ai%20ai.3gp"));
            sonidos.add(new Sonido("Se oye como una especie de golpecillos irregulares", R.raw.transmision, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=xhSorJUu0vI"));
            sonidos.add(new Sonido("Seguro dental", R.raw.segdent, Personaje.HOMER, Personaje.MARGE, Personaje.LENNY).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/Seguro-Dental%2C-Lisa-necesita-un-aparato.3gp"));
            sonidos.add(new Sonido("Seguro que es una feria de ciencia ficción?", R.raw.soloveoempollones, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=CAALcWSZ6cE"));
            sonidos.add(new Sonido("Señor Smithers no entiendo 2700 de mis nuevas tareas", R.raw.tareas, Personaje.HOMER).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/tareas.3gp"));
            sonidos.add(new Sonido("Shhh, calla Lisa", R.raw.shhh_calla_lisa, Personaje.LISA));
            sonidos.add(new Sonido("Si estás salvado da palmadas", R.raw.siestassalvado, Personaje.OTROS).setVideoUrl("http://www.youtube.com/watch?v=DmGC2-dhKgU"));
            sonidos.add(new Sonido("Si, llévame hoy al fútbol", R.raw.llevamehoy, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=GKBYDlhupDo"));
            sonidos.add(new Sonido("Siiii", R.raw.siiiii, Personaje.OTROS).setVideoUrl("http://www.youtube.com/watch?v=monY0sVpkeA"));
            sonidos.add(new Sonido("Sin tele y sin cerveza...", R.raw.sin_tele, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Skinner en Vietnam", R.raw.joni, Personaje.SKINNER));
            sonidos.add(new Sonido("Socorro! Esta rozando mi zona especial", R.raw.rozando_mi_zona_especial, Personaje.RALPH));
            sonidos.add(new Sonido("Solo la tele me respeta", R.raw.solo_la_tele_me_respeta, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=jUL9O0zKPqw"));
            sonidos.add(new Sonido("Soy Homer Simp...", R.raw.soy_homer_simp, Personaje.OTROS).setVideoUrl("http://www.youtube.com/watch?v=4EGO9mddcns"));
            sonidos.add(new Sonido("Soy Lionel Hutz, abogado", R.raw.loinel, Personaje.OTROS).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/loinel.3gp"));
            sonidos.add(new Sonido("Soy el Homer malo", R.raw.soy_el_homer_malo, Personaje.HOMER));
            sonidos.add(new Sonido("Soy el ángel de la muerte", R.raw.angel_muerte, Personaje.OTROS));
            sonidos.add(new Sonido("Soy la O de la palabra Hola", R.raw.soylao, Personaje.HOMER));
            sonidos.add(new Sonido("Soy un barranco", R.raw.soy_un_barranco, Personaje.RALPH));
            sonidos.add(new Sonido("Soy un tío trompa", R.raw.soy_un_tio_trompa, Personaje.HOMER));
            sonidos.add(new Sonido("Soy un unicornio retrasado", R.raw.unicornio, Personaje.RALPH));
            sonidos.add(new Sonido("Spider cerdo", R.raw.spidercerdo, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=HrpTd216l34"));
            sonidos.add(new Sonido("Sr. Thompson", R.raw.srthomson, Personaje.HOMER));
            sonidos.add(new Sonido("Sálvame Superman", R.raw.salvame_superman, Personaje.HOMER));
            sonidos.add(new Sonido("Te gusta algo?", R.raw.tegustalgo, Personaje.RALPH));
            sonidos.add(new Sonido("Tecla cualquiera", R.raw.tecla, Personaje.HOMER));
            sonidos.add(new Sonido("Tenga 5$", R.raw.tenga5, Personaje.MARGE));
            sonidos.add(new Sonido("Tetillas Larue", R.raw.tetillas, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Tipo de incógnito", R.raw.tipo_incong, Personaje.HOMER));
            sonidos.add(new Sonido("Tituriti", R.raw.tituriti, Personaje.HOMER, Personaje.BART));
            sonidos.add(new Sonido("Todavía se podría comer", R.raw.todavia_se_podria_comer, Personaje.HOMER).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/todavia%20se%20podria%20comer.3gp"));
            sonidos.add(new Sonido("Todo ha salido a pedir de Milhouse", R.raw.apedirde, Personaje.MILHOUSE).setVideoUrl("http://www.youtube.com/watch?v=TFRoRF9FvbI"));
            sonidos.add(new Sonido("Todos locos", R.raw.todoslocos, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=URWLnItt5p0"));
            sonidos.add(new Sonido("Tomaco", R.raw.tomaco, Personaje.OTROS));
            sonidos.add(new Sonido("Trabajo por dinero", R.raw.trabajo, Personaje.HOMER, Personaje.BURNS, Personaje.CANCIONES));
            sonidos.add(new Sonido("Ummm cerveza", R.raw.mm_cerveza, Personaje.HOMER));
            sonidos.add(new Sonido("Untiobe Suconazo", R.raw.untiobe_suconazo, Personaje.BART, Personaje.MOE).setVideoUrl("https://dl.dropbox.com/u/31111602/raw/mp4/Untiobe_Suconazo.3gp"));
            sonidos.add(new Sonido("Uy el mafioso se ha enfadado...", R.raw.mafiosoenfadado, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=f6M7kVD9sjs"));
            sonidos.add(new Sonido("Vaaaya, hay un bichito", R.raw.bichito, Personaje.HOMER, Personaje.MARGE));
            sonidos.add(new Sonido("Vamos a palmar!", R.raw.palmar, Personaje.HOMER));
            sonidos.add(new Sonido("Venga Lenny anda!!", R.raw.venga_lenny, Personaje.HOMER, Personaje.LENNY));
            sonidos.add(new Sonido("Viva nuestro conductor", R.raw.conductor, Personaje.CANCIONES, Personaje.SKINNER));
            sonidos.add(new Sonido("Voy a matar a Moe", R.raw.moe, Personaje.HOMER));
            sonidos.add(new Sonido("Vámonos átomos", R.raw.vamonos_atomos, Personaje.OTROS));
            sonidos.add(new Sonido("Wiggum", R.raw.wiggum, Personaje.WIGGUM));
            sonidos.add(new Sonido("Y de beber... albóndigas", R.raw.beber_albondigas, Personaje.HOMER));
            sonidos.add(new Sonido("Ya lo ven", R.raw.yaloven, Personaje.BURNS, Personaje.CANCIONES).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/yaloven.3gp"));
            sonidos.add(new Sonido("Ya me ha pegado Lisa de niño y Lisa de niña", R.raw.lisa_nino_nina, Personaje.RALPH));
            sonidos.add(new Sonido("Ya veremos cariño, ya veremos", R.raw.ya_veremos, Personaje.HOMER, Personaje.LISA));
            sonidos.add(new Sonido("Yo me llamo Ralph", R.raw.yomellamoralph, Personaje.RALPH).setVideoUrl("http://www.youtube.com/watch?v=davsl0wL7Is"));
            sonidos.add(new Sonido("Yo me voy por mi izquierda", R.raw.yo_me_voy_por_mi_izquierda, Personaje.BURNS, Personaje.CANCIONES));
            sonidos.add(new Sonido("Yo no", R.raw.yono, Personaje.OTROS));
            sonidos.add(new Sonido("Yo no 2", R.raw.yono2, Personaje.OTROS));
            sonidos.add(new Sonido("Yo no he sido", R.raw.bart, Personaje.BART).setVideoUrl("http://dl.dropbox.com/u/31111602/raw/mp4/yo-no-he-sido.3gp"));
            sonidos.add(new Sonido("Yo secundo la moción", R.raw.yo_secundo_la_mocion, Personaje.HOMER));
            sonidos.add(new Sonido("Yo solo voy a ir haciendo así", R.raw.yosolo, Personaje.HOMER).setVideoUrl("http://www.youtube.com/watch?v=VrbU6AW4Gb0"));
            sonidos.add(new Sonido("Yo soy el señor Bruns", R.raw.bruns, Personaje.BURNS).setVideoUrl("http://www.youtube.com/watch?v=D55GQKxdjgg"));
            sonidos.add(new Sonido("Yo tampoco puedo decírtelo Ralph", R.raw.atiquientepregunta, Personaje.RALPH));
            sonidos.add(new Sonido("Yogurlado", R.raw.yogurlado, Personaje.HOMER));
            sonidos.add(new Sonido("Yojuuu", R.raw.yoju, Personaje.HOMER));
            sonidos.add(new Sonido("Yuhuuu", R.raw.yuhuu, Personaje.HOMER));
            sonidos.add(new Sonido("Zaaaap", R.raw.zap, Personaje.OTROS));
            sonidos.add(new Sonido("Zombie Flanders", R.raw.zombie_flanders, Personaje.HOMER, Personaje.BART, Personaje.FLANDERS).setVideoUrl("http://www.youtube.com/watch?v=NHliJ3b_t3o"));
            sonidos.add(new Sonido("Ñaca Ñaca Ñaca Me duele la barriga de ganas de quererte", R.raw.naca_naca_naca, Personaje.HOMER, Personaje.CANCIONES).setVideoUrl("http://www.youtube.com/watch?v=1hxgw_4SXPM"));
            sonidos.add(new Sonido("Último gustazo como soltero", R.raw.ultimo, Personaje.HOMER));

            Collections.sort(sonidos, new Comparator<Sonido>() {
                public int compare(Sonido s1, Sonido s2) {
                    return s1.getNombre().compareTo(s2.getNombre());
                }
            });
        }
    }


}
